version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: music-store-mysql
    restart: always
    environment:
      MYSQL_DATABASE: musicstore_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: project
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - musicstore-network

  music-store:
    image: beblue/music-store-api
    container_name: music-store-api
    restart: always
    volumes:
      - ./wait-for.sh:/root/wait-for.sh
    ports:
      - 8080:8080
    depends_on:
      - mysql
    # Deveria customizar o wait-for para aguardar a inicialização do mysql(criação da base) por completo, está funcionando, porem somente na criação do container
    # o mysql demora para iniciar e o music-store reinicia 2/3x até subir o server por completo nas proximas inicializações não há esse problema.
    command: sh -c '/root/wait-for.sh mysql:3306'
    networks:
      - musicstore-network

networks:
  musicstore-network:
    driver: bridge