## -- DEVELOPMENT / DEFAULT APPLICATION --

# Custom properties

application:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  environment: dev

spotify:
  client:
    id: 1228515c3a654087b2a33907226e09e9
    secret: c370e93002bc43fbaf64a6f2c582d086

# Server Properties

spring:
  datasource:
    url: jdbc:h2:file:~/musicstore_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    url: jdbc:h2:file:~/musicstore_db
    user: root
    password: root
    baseline-on-migrate: true
    validate-on-migrate: false