# Custom properties

application:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  environment: test

---
# Server Properties

spring:

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:springx

  flyway:
    url: jdbc:h2:mem:springx