## -- TESTS APPLICATION --
debug: true

# Custom properties
application:
  environment: test

# Server Properties
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1

server:
  port: 9999