## -- PRODUCTION APPLICATION --

application:
  environment: prod

spring:

  datasource:
    url: jdbc:mysql://mysql:3306/musicstore_db
    username: project
    password: password

  jpa:
    properties:
      hibernate:
        show_sql: false