## -- DEFAULT / DEVELOPMENT APPLICATION --

# Custom properties

application:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  environment: default

  mq:
    sale:
      queue:
        name: sales
      exchange:
        name: sales-exchange
        routing-key: musicstore.sales

spotify:
  client:
    id: ${SPOTFY_ID:}
    secret: ${SPOTFY_SECRET:}

# Server Properties

spring:
  datasource:
    url: jdbc:h2:nio:./db/musicstore_db;MODE=MySQL
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    validate-on-migrate: false

  rabbitmq:
    host: localhost
    username: rabbitmq
    password: rabbitmq